### PR TITLE
13 add test chain with chain extension and currencies

### PR DESCRIPTION
**Pull request by b-yap**
This testchain is based on [substrate-contracts-node](https://github.com/paritytech/substrate-contracts-node).
But since we're aiming for version _`polkadot-v0.9.18`_ , it looks a little different from their main branch. see its tag _`v0.12.0`_, especially the [node module](https://github.com/paritytech/substrate-contracts-node/tree/v0.12.0/node).

Since the `Chainextension`, needs the `CurrencyId`, I took a snippet from spacewalk's [currency.rs](https://github.com/pendulum-chain/spacewalk/blob/main/pallets/spacewalk/src/currency.rs#L24) and just added it in [runtime's lib.rs](https://github.com/pendulum-chain/pendulum-amm/pull/14/files#diff-0745aac8a9122df3f864fa8f72097995fc74848298eab2c7244e3d24b85a05d7R293). 

This does compile, and the contract was successfully added.
 But tbh I don't know what the expected behaviors are for some messages like `deposit_assest_1`, `withdraw`.

### CODE REVIEW

**Comment by ebma** [comment]
Hey @b-yap, I added the EUR asset to the endowed accounts as well so that now every one of the test accounts has some initial funding of both. I tested if the AMM works, and while deploying works, depositing fails with a `ContractReverted` message.
I saw that you removed the `AlphaNum4` stuff from the runtime and only added the `AlphaNum12` for the enum so I guess/hope that re-adding `AlphaNum4` fixes this issue. Is there a reason you removed it in the first place?

**Comment by b-yap** [comment]
Hi @ebma ,
You are right, the Byte4  type, the `AlphaNum4` fixed it. Thank you!
( I removed it because I thought it'll be ok without it, seeing the `type AssetCode = [u8; 12]` )

I've tested the `deposit_asset_1` and it works fine when amount is _1 unit_.
```
depositAsset1(amount: Balance): Result<u128, PendulumAmmAmmError>
balances:Withdraw

contracts:ContractEmitted

tokens:Endowed

currencies:Transferred

tokens:Endowed

currencies:Transferred

contracts:ContractEmitted

contracts:ContractEmitted

contracts:ContractEmitted

balances:Transfer

balances:Reserved

system:ExtrinsicSuccess
```

**Comment by b-yap** [comment]
Some issues that needed to be fixed: check [stack exchange question](https://substrate.stackexchange.com/questions/2870/cargo-contract-throws-error-about-supplied-arguments-in-inkconstructor-f?noredirect=1&lq=1)

Also, the `num-integer` has moved the `Root` implementation of `u128` datatype, hence the added [feature](https://github.com/pendulum-chain/pendulum-amm/pull/14/files#diff-282423724f5b10467644976199409d42482926d579ebcf909e4d40ce1daeb523R23).

Kindly review again @ebma; I also updated the [README](https://github.com/pendulum-chain/pendulum-amm/pull/14/files#diff-e6f63f8e761dd43aa4bf009173e7d5059aad07b2fcdf7d9b9eba02f85afea810).

**Comment by ebma** [comment]
I was only facing this issue because I tried to deposit 1000 Units but the accounts only hold 1 Unit of EUR and USDC each. So I guess everything works fine and this PR can finally be merged. :+1:

**Pull request merged**
